### ISSUE TITLE
Recipe issue with K2 + 248k

### ISSUE THREAD

**Issue by shadoxxhd** [ShingenPizza/Smooth_Fluids#1]
When Krastorio2 is enabled, the 248k mod adjusts some recipes in the data-final-updates phase, by replacing the input side only. This means the in-out balance is severely distorted.

Since Smooth_Fluids currently uses data-updates, a dependency isn't sufficient to fix this issue - the easiest solution would be to move the smoothing logic into data-final-fixes, but if that causes any issues, either adding an additional pass in final-fixes that explicitly checks for one-sided recipe changes, or determining recipe processing time depending on what mods are loaded (/having a manual recipe blacklist(/"edit in final fixes" list)) should also work.

**Comment by ShingenPizza** [comment]
ah, this.
back when you posted this on Factorio modding portal i took a look at Krastorio2/248k code and tried to find the problematic recipes to 'recreate' the bug first, but i didn't find anything right away, and it eventually slipped my mind.

i took a look again, found the oil processing stuff that was indeed broken, and it looks like moving the main code to data-final-fixes and adding those mods to dependencies fixed it.

if you encounter any further issues let me know!

**Comment by shadoxxhd** [comment]
I guess I should have told you the exact broken recipe and responsible file/line...
